### ISSUE TITLE
Not a issue

### ISSUE THREAD

**Issue by skrimxyz** [imtorchedbud/Qb-Vehiclekeys#1]
Can you make it like when you lockpick the door also to use lockpick to start the engine for the car and not use that drawtext?

**Comment by HydrixScripts** [comment]
of course! give me a day or two im currently working on alot of projects :)
i should have something for ya soon

**Comment by HydrixScripts** [comment]
go ahead and grab the update file you should be able to lockpick the ignition as well as the 2d hotwire it is mandatory to keep the vehicle disabled until lockpicked or keys found.
